require('dotenv').config()
const mongoose = require('mongoose')
const Product = require('./models/Product')
const { assignSlugsToProducts } = require('./utils/productSlug')

const products = [
  {
    name: 'Vitamin D3 + K2 Complex (5000 IU)',
    description: 'High-potency Vitamin D3 paired with K2 (MK-7) for optimal calcium absorption and bone health. Third-party tested, non-GMO, gluten-free. 90 softgel capsules.',
    price: 24.99,
    comparePrice: 34.99,
    category: 'Vitamins',
    tags: ['vitamin d', 'vitamin k2', 'bone health', 'immune support'],
    images: [{ url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600', source: 'link' }],
    stock: 120,
    isFeatured: true,
    isPublished: true,
    rating: 4.8,
    numReviews: 342,
  },
  {
    name: 'Omega-3 Fish Oil (2000mg)',
    description: 'Ultra-pure fish oil with 1200mg EPA & DHA per serving. Molecularly distilled to remove heavy metals. Supports heart, brain, and joint health. 90 softgels.',
    price: 29.99,
    comparePrice: 44.99,
    category: 'Supplements',
    tags: ['omega-3', 'fish oil', 'heart health', 'brain health'],
    images: [{ url: 'https://images.unsplash.com/photo-1626716493137-b67fe9501e76?w=600', source: 'link' }],
    stock: 85,
    isFeatured: true,
    isPublished: true,
    rating: 4.7,
    numReviews: 218,
  },
  {
    name: 'Magnesium Glycinate 400mg',
    description: 'Highly bioavailable magnesium glycinate for muscle recovery, better sleep, and stress relief. Gentle on the stomach. No laxative effect. 120 capsules.',
    price: 22.99,
    comparePrice: 0,
    category: 'Vitamins',
    tags: ['magnesium', 'sleep', 'muscle recovery', 'stress relief'],
    images: [{ url: 'https://images.unsplash.com/photo-1550572017-4fcdbb59cc32?w=600', source: 'link' }],
    stock: 95,
    isFeatured: true,
    isPublished: true,
    rating: 4.9,
    numReviews: 487,
  },
  {
    name: 'Whey Protein Isolate – Vanilla (2lb)',
    description: 'Premium whey protein isolate with 27g protein per serving and less than 1g fat & carbs. Grass-fed, hormone-free. Perfect post-workout recovery shake.',
    price: 49.99,
    comparePrice: 69.99,
    category: 'Nutrition',
    tags: ['protein', 'whey', 'muscle building', 'post-workout'],
    images: [{ url: 'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=600', source: 'link' }],
    stock: 60,
    isFeatured: true,
    isPublished: true,
    rating: 4.6,
    numReviews: 163,
  },
  {
    name: 'Ashwagandha KSM-66 (600mg)',
    description: 'Clinically studied KSM-66 ashwagandha root extract. Reduces cortisol, supports energy levels, and promotes a calm focused mind. Vegan, 60 capsules.',
    price: 27.99,
    comparePrice: 39.99,
    category: 'Supplements',
    tags: ['ashwagandha', 'adaptogen', 'stress', 'energy'],
    images: [{ url: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=600', source: 'link' }],
    stock: 78,
    isFeatured: true,
    isPublished: true,
    rating: 4.8,
    numReviews: 295,
  },
  {
    name: 'Probiotic 50 Billion CFU (10 Strains)',
    description: 'Advanced probiotic formula with 50 billion CFU across 10 clinically studied strains. Supports gut health, digestion, and immune function. Shelf-stable, 60 capsules.',
    price: 34.99,
    comparePrice: 49.99,
    category: 'Supplements',
    tags: ['probiotic', 'gut health', 'digestion', 'immune'],
    images: [{ url: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=600', source: 'link' }],
    stock: 55,
    isFeatured: true,
    isPublished: true,
    rating: 4.5,
    numReviews: 189,
  },
  {
    name: 'Collagen Peptides Powder (Unflavored)',
    description: 'Hydrolyzed Type I & III collagen peptides for skin elasticity, hair, nails, and joint support. Grass-fed, pasture-raised. Dissolves easily in any beverage. 300g.',
    price: 37.99,
    comparePrice: 54.99,
    category: 'Nutrition',
    tags: ['collagen', 'skin health', 'joints', 'anti-aging'],
    images: [{ url: 'https://images.unsplash.com/photo-1559181567-c3190ca9959b?w=600', source: 'link' }],
    stock: 70,
    isFeatured: false,
    isPublished: true,
    rating: 4.7,
    numReviews: 412,
  },
  {
    name: 'Pre-Workout Energy Formula',
    description: 'Clean pre-workout with 200mg natural caffeine, beta-alanine, citrulline malate, and B vitamins. No crash, no artificial dyes. 30 servings – Blue Raspberry.',
    price: 39.99,
    comparePrice: 54.99,
    category: 'Fitness',
    tags: ['pre-workout', 'energy', 'performance', 'gym'],
    images: [{ url: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600', source: 'link' }],
    stock: 45,
    isFeatured: true,
    isPublished: true,
    rating: 4.4,
    numReviews: 127,
  },
  {
    name: 'Zinc + Copper Balance (25mg)',
    description: 'Zinc bisglycinate chelate paired with copper for proper mineral balance. Supports immune function, testosterone levels, and skin health. 120 capsules.',
    price: 16.99,
    comparePrice: 0,
    category: 'Vitamins',
    tags: ['zinc', 'copper', 'immune', 'testosterone'],
    images: [{ url: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600', source: 'link' }],
    stock: 100,
    isFeatured: false,
    isPublished: true,
    rating: 4.6,
    numReviews: 98,
  },
  {
    name: 'Creatine Monohydrate (500g)',
    description: 'Pure micronized creatine monohydrate — the most researched supplement for strength, power, and lean muscle gain. Unflavored, mixes instantly. Vegan-friendly.',
    price: 24.99,
    comparePrice: 34.99,
    category: 'Fitness',
    tags: ['creatine', 'strength', 'muscle', 'performance'],
    images: [{ url: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600', source: 'link' }],
    stock: 90,
    isFeatured: false,
    isPublished: true,
    rating: 4.9,
    numReviews: 524,
  },
  {
    name: 'Multivitamin for Women (Whole Food)',
    description: 'Comprehensive whole-food multivitamin with 25+ vitamins & minerals plus botanical blends. Iron, folate, B12, and biotin for energy and vitality. 60 capsules.',
    price: 32.99,
    comparePrice: 44.99,
    category: 'Vitamins',
    tags: ['multivitamin', 'womens health', 'energy', 'whole food'],
    images: [{ url: 'https://images.unsplash.com/photo-1550572017-4fcdbb59cc32?w=600', source: 'link' }],
    stock: 65,
    isFeatured: true,
    isPublished: true,
    rating: 4.7,
    numReviews: 231,
  },
  {
    name: 'Sleep Support Formula (Melatonin + L-Theanine)',
    description: 'Gentle sleep blend with 3mg melatonin, 200mg L-theanine, and magnesium. Fall asleep faster, stay asleep longer. Non-habit forming. 60 tablets.',
    price: 19.99,
    comparePrice: 28.99,
    category: 'Wellness',
    tags: ['sleep', 'melatonin', 'relaxation', 'stress'],
    images: [{ url: 'https://images.unsplash.com/photo-1511295742362-92c96b1cf484?w=600', source: 'link' }],
    stock: 110,
    isFeatured: false,
    isPublished: true,
    rating: 4.6,
    numReviews: 376,
  },
  {
    name: 'Turmeric Curcumin + BioPerine (1500mg)',
    description: 'High-potency turmeric with 95% curcuminoids and BioPerine black pepper extract for 2000% better absorption. Anti-inflammatory and antioxidant support. 90 capsules.',
    price: 26.99,
    comparePrice: 38.99,
    category: 'Supplements',
    tags: ['turmeric', 'curcumin', 'anti-inflammatory', 'antioxidant'],
    images: [{ url: 'https://images.unsplash.com/photo-1615485500704-8e990f9900f7?w=600', source: 'link' }],
    stock: 75,
    isFeatured: false,
    isPublished: true,
    rating: 4.8,
    numReviews: 302,
  },
  {
    name: 'BCAA 2:1:1 Powder – Watermelon (300g)',
    description: 'Branched-chain amino acids in optimal 2:1:1 ratio (leucine, isoleucine, valine). Reduces muscle soreness, supports recovery and endurance. 30 servings.',
    price: 28.99,
    comparePrice: 39.99,
    category: 'Fitness',
    tags: ['bcaa', 'amino acids', 'recovery', 'endurance'],
    images: [{ url: 'https://images.unsplash.com/photo-1594381898411-846e7d193883?w=600', source: 'link' }],
    stock: 50,
    isFeatured: false,
    isPublished: true,
    rating: 4.3,
    numReviews: 144,
  },
  {
    name: 'Vitamin C 1000mg with Rosehip',
    description: 'High-dose Vitamin C with natural rosehip extract for enhanced bioavailability. Buffered, gentle on the stomach. Supports immune defense, collagen synthesis, and skin glow. 120 tablets.',
    price: 18.99,
    comparePrice: 24.99,
    category: 'Vitamins',
    tags: ['vitamin c', 'immune', 'skin health', 'antioxidant'],
    images: [{ url: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?w=600', source: 'link' }],
    stock: 140,
    isFeatured: false,
    isPublished: true,
    rating: 4.5,
    numReviews: 267,
  },
  {
    name: 'Plant-Based Protein – Chocolate (1.5lb)',
    description: 'Organic pea & brown rice protein blend with 22g protein per serving. No artificial sweeteners, dairy-free, soy-free. Perfect for vegans and sensitive stomachs.',
    price: 44.99,
    comparePrice: 59.99,
    category: 'Nutrition',
    tags: ['vegan protein', 'plant based', 'pea protein', 'dairy free'],
    images: [{ url: 'https://images.unsplash.com/photo-1553531889-56cc480ac5cb?w=600', source: 'link' }],
    stock: 40,
    isFeatured: true,
    isPublished: true,
    rating: 4.4,
    numReviews: 98,
  },
]

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI)
    console.log('Connected to MongoDB')

    await Product.deleteMany({})
    console.log('Cleared existing products')

    await assignSlugsToProducts(Product, products)
    const inserted = await Product.insertMany(products)
    console.log(`Seeded ${inserted.length} products`)

    await mongoose.disconnect()
    console.log('Done')
    process.exit(0)
  } catch (err) {
    console.error('Seed failed:', err)
    process.exit(1)
  }
}

seed()
